#cloud-config
users:
    - name: deploy
      groups: sudo
      shell: /bin/bash
      sudo:
          - 'ALL=(ALL) NOPASSWD:ALL'
      # If debugging access needed
      # ssh_authorized_keys:
      #     - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFP57DT5rEirUZt/hfXmCAPKS/nAVXL9dObGhX9lWd+p
disable_root: true

packages:
    - git
    - python3
    - python3-apt
package_update: true
package_upgrade: true
